#!/bin/bash
set -e
run()  {
	CMD=$1
	echo $CMD
	eval $CMD
	echo "\n"
}

runSilently()  {
	CMD=$1
	echo $CMD
	(eval $CMD &) &> /dev/null
	echo "\n"
}

getAbsolutePath() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}
