#!/bin/bash
set -e
source common/variables
source common/functions

waitInterval="5s"
################################################################################
########## PREPARE WORKSPACE FOR TEST CASE #####################################
echo "Cleaning output directory"
rm -Rf $OUT_DIR
testName=$1
dockerImage=$2
inputDirectory="input/test/$3"
outputDirectory="$OUT_DIR/$testName/"
mkdir -p $outputDirectory
hostDataPath=$(getAbsolutePath $outputDirectory)
cp -R $inputDirectory/* $outputDirectory
containerDataPath="/home/besu"
################################################################################

################################################################################
########## RUN IMPORT COMMAND ##################################################
runImportCommand $testName $dockerImage $hostDataPath $containerDataPath
sleep $waitInterval
shutdownDocker $testName
################################################################################

################################################################################
########## RUN BESU WITH JSON RPC ##############################################
#docker run -p 8545:8545 $dockerImage --rpc-http-enabled --network=dev
################################################################################

runImportCommand() {
	testName=$1
	echo "[$testName] Running import command"
	dockerImage=$2
	hostDataPath=$3
	containerDataPath=$4
	CMD="docker run --name $testName -d --mount type=bind,source=$hostDataPath,target=$containerDataPath $dockerImage --data-path=$containerDataPath --genesis-file=$containerDataPath/genesis.json blocks import --from=$containerDataPath/ropsten-10-blocks.bin"
	echo $CMD
	eval $CMD
}
