#!/bin/bash
set -e
source common/variables
source common/functions

sh scripts/run-migration-test-case Before_Versioning_Was_Enabled docker.io/pegasyseng/pantheon:1.2.0 version0
sh scripts/run-migration-test-case After_Versioning_Was_Enabled docker.io/pegasyseng/pantheon:1.2.1 version1
